language: crystal
env:
  global:
    - DATABASE_PATH=postgres://postgres@/silvio_test
      CRYSTAL_ENV=test
matrix:
  include:
  - name: "Unit tests for Crystal"
    env: TEST_SCRIPT="crystal spec"
  - name: "High-level testing with ping"
    env: TEST_SCRIPT="spec/ping/test-server.sh"
services:
  - docker
  - postgresql
before_install:
  sudo apt-get install -y libsqlite3-dev jq
before_script:
  psql -c 'create database silvio_test;' -U postgres
script: $TEST_SCRIPT
after_script:
  psql -c 'drop database silvio_test;' -U postgres
